#ifndef OBLO_INCLUDE_SURFELS_BUFFER_BINDINGS
#define OBLO_INCLUDE_SURFELS_BUFFER_BINDINGS

#define SURFEL_GRID_BINDING 50
#define SURFEL_GRID_DATA_BINDING 51
#define SURFEL_STACK_BINDING 52
#define SURFEL_SPAWN_DATA_BINDING 53
#define SURFEL_DATA_BINDING 54
#define SURFEL_LIGHTING_DATA_IN_BINDING 55
#define SURFEL_LIGHTING_DATA_OUT_BINDING 56
#define SURFEL_LIGHT_ESTIMATOR_DATA_BINDING 57
#define SURFEL_METRICS_BINDING 58
#define SURFEL_LAST_USAGE_BINDING 59

#endif