#version 460

#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_KHR_shader_subgroup_quad : require

#include <pathtracing/pathtracing>
#include <renderer/camera>
#include <renderer/motion_vectors>
#include <renderer/random/random>
#include <renderer/random/sampling>
#include <renderer/shading/pbr>
#include <renderer/textures>
#include <visibility/visibility_utils>

layout(binding = 16) uniform b_CameraBuffer
{
    camera_buffer g_Camera;
};

layout(binding = 11) uniform accelerationStructureEXT u_SceneTLAS;

layout(binding = 20, rgba16f) uniform restrict image2D t_OutShadedImage;
layout(binding = 21, r32ui) uniform restrict uimage2D t_SamplesCount;
layout(binding = 22, OBLO_MOTION_VECTORS_FORMAT) uniform restrict readonly image2D t_InMotionVectors;

layout(location = 0) rayPayloadEXT pathtracing_payload r_Payload;

layout(push_constant) uniform c_PushConstants
{
    uint randomSeed;
}
g_Constants;

const uint g_SamplesPerPixel = 2;
const uint g_MaxBounces = 4;
const uint g_MaxSamplesPerPixel = 1u << 14;

void main()
{
    const vec2 positionNDC = screen_to_ndc(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy);
    const ivec2 screenPos = ivec2(gl_LaunchIDEXT.xy);

    // For now we just use motion vectors to reset the accumulation when the camera or the object moves
    uint previousSamplesCount = imageLoad(t_SamplesCount, screenPos).r;

    const vec2 motionVector = imageLoad(t_InMotionVectors, screenPos).xy;
    const vec3 history = imageLoad(t_OutShadedImage, screenPos).rgb;

    if (dot(motionVector, motionVector) > 1e-7)
    {
        previousSamplesCount = 0;
    }

    const uint newSamplesCount = previousSamplesCount + g_SamplesPerPixel;

    if (newSamplesCount >= g_MaxSamplesPerPixel)
    {
        return;
    }

    const float tMin = 1e-2f;
    const float tMax = 1e6f;

    r_Payload.seed = random_seed(g_Constants.randomSeed, gl_LaunchIDEXT.x + gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x);

    vec3 accumulated = vec3(0);

    for (uint sampleIdx = 0; sampleIdx < g_SamplesPerPixel; ++sampleIdx)
    {
        r_Payload.radiance = vec3(0.0);
        r_Payload.throughput = vec3(1.0);
        r_Payload.origin = g_Camera.position;
        r_Payload.direction = camera_ray_direction(g_Camera, positionNDC);
        r_Payload.done = false;

        for (uint depth = 0; depth < g_MaxBounces; ++depth)
        {
            traceRayEXT(u_SceneTLAS,
                gl_RayFlagsOpaqueEXT,
                0xff, // cull mask
                0,    // STB record offset
                0,    // STB record stride
                0,    // Miss index
                r_Payload.origin,
                tMin,
                r_Payload.direction,
                tMax,
                0 // payload location
            );

            if (r_Payload.done)
            {
                break;
            }
        }

        accumulated += r_Payload.radiance;
    }

    const vec3 sampleAvg = accumulated / float(g_SamplesPerPixel);
    const vec3 newAverage = history + (sampleAvg - history) * (float(g_SamplesPerPixel) / float(newSamplesCount));

    imageStore(t_OutShadedImage, screenPos, vec4(newAverage, 1));
    imageStore(t_SamplesCount, screenPos, uvec4(newSamplesCount, 0, 0, 0));
}