#ifndef OBLO_INCLUDE_SURFELS_BUFFER_BINDINGS
#define OBLO_INCLUDE_SURFELS_BUFFER_BINDINGS

#define SURFEL_GRID_BINDING 50
#define SURFEL_STACK_BINDING 51
#define SURFEL_SPAWN_DATA_BINDING 52
#define SURFEL_DATA_BINDING 53

#endif