#version 460

#extension GL_ARB_gpu_shader_int64 : require
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_samplerless_texture_functions : require
#extension GL_GOOGLE_include_directive : require
#extension GL_KHR_shader_subgroup_quad : require
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require

#include <deferred/gbuffer>
#include <renderer/geometry/barycentric>
#include <renderer/geometry/ray>
#include <renderer/geometry/volumes>
#include <renderer/instances>
#include <renderer/material>
#include <renderer/math>
#include <renderer/meshes/mesh_attributes>
#include <renderer/meshes/mesh_data>
#include <renderer/meshes/mesh_indices>
#include <renderer/meshes/mesh_table>
#include <renderer/meshes/skinning>
#include <renderer/quad>
#include <renderer/shading/normal_mapping>
#include <renderer/shading/pbr>
#include <renderer/shading/pbr_utility>
#include <renderer/textures>
#include <renderer/transform>
#include <visibility/visibility_buffer>
#include <visibility/visibility_utils>

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 16) uniform b_CameraBuffer
{
    camera_buffer g_Camera;
};

layout(binding = 11, rg32ui) uniform restrict readonly uimage2D t_InVisibilityBuffer;

layout(binding = 12, rgba16f) uniform restrict writeonly image2D t_OutGBuffer0;
layout(binding = 13, rgba16f) uniform restrict writeonly image2D t_OutGBuffer1;
layout(binding = 14, rgba16f) uniform restrict writeonly image2D t_OutGBuffer2;
layout(binding = 15, rgba16f) uniform restrict writeonly image2D t_OutGBuffer3;

void write_empty_pixel(in ivec2 screenPos)
{
    gbuffer0 g0;

    // We use negative values on roughness to mark
    g0.roughness = -1.f;

    imageStore(t_OutGBuffer0, screenPos, gbuffer_pack(g0));
}

void main()
{
    const uvec2 localGroupId = quad_remap_lane_8x8(gl_LocalInvocationIndex);
    const ivec2 screenPos = ivec2(gl_WorkGroupID.xy * 8 + localGroupId);
    const uvec2 resolution = imageSize(t_InVisibilityBuffer);

    if (screenPos.x >= resolution.x || screenPos.y >= resolution.y)
    {
        return;
    }

    // Parse the visibility buffer to find which triangle we are processing
    const uvec4 visBufferData = imageLoad(t_InVisibilityBuffer, screenPos);
    visibility_buffer_data vb;

    if (!visibility_buffer_parse(visBufferData.xy, vb))
    {
        write_empty_pixel(screenPos);
        return;
    }

    // Read the instance data we need
    const mesh_handle mesh = OBLO_INSTANCE_DATA(vb.instanceTableId, i_MeshHandles, vb.instanceId);
    const transform transform = OBLO_INSTANCE_DATA(vb.instanceTableId, i_TransformBuffer, vb.instanceId);
    const gpu_material material = OBLO_INSTANCE_DATA(vb.instanceTableId, i_MaterialBuffer, vb.instanceId);

    const bool hasSkinningInstanceData = OBLO_HAS_INSTANCE_DATA(vb.instanceTableId, i_JointSkinningChunksBuffer);

    triangle triangleWS;
    vec2 triangleUV0[3];
    vec3 triangleNormal[3];
    vec3 triangleTangent[3];
    vec3 triangleBitangent[3];

    // Read the mesh data
    const mesh_table meshTable = mesh_table_fetch(mesh);
    const uvec3 vertexIndices = mesh_get_meshlet_indices(meshTable, mesh, vb.meshletId, vb.meshletTriangleId);

    const bool hasSkinningMeshAttributes = mesh_table_has_attributes(meshTable,
        (1u << OBLO_VERTEX_ATTRIBUTE_JOINT_INDICES) | (1u << OBLO_VERTEX_ATTRIBUTE_JOINT_WEIGHTS));

    // Read the vertex data and transform everything in world space, we do lighting calculation in that space
    [[unroll]] for (uint i = 0; i < 3; ++i)
    {
        const uint vertexId = vertexIndices[i];

        const vec3 vertexPosition = mesh_get_position(meshTable, vertexId);
        triangleWS.v[i] = (transform.localToWorld * vec4(vertexPosition, 1)).xyz;

        const vec3 vertexNormal = mesh_get_normal(meshTable, vertexId);
        triangleNormal[i] = vertexNormal;

        const vec3 vertexTangent = mesh_get_tangent(meshTable, vertexId);
        triangleTangent[i] = vertexTangent;

        const vec3 vertexBitangent = mesh_get_bitangent(meshTable, vertexId);
        triangleBitangent[i] = vertexBitangent;

        triangleUV0[i] = mesh_get_uv0(meshTable, vertexId);
    }

    const bool performSkinning = hasSkinningInstanceData && hasSkinningMeshAttributes;

    if (performSkinning)
    {
        const skinning_joint_chunks chunks =
            OBLO_INSTANCE_DATA(vb.instanceTableId, i_JointSkinningChunksBuffer, vb.instanceId);

        [[unroll]] for (uint i = 0; i < 3; ++i)
        {
            const uint vertexId = vertexIndices[i];
            const vec3 inPosition = mesh_get_position(meshTable, vertexId);

            const uvec4 inJointIndices = mesh_get_joint_indices(meshTable, vertexId);
            const vec4 inJointWeights = mesh_get_joint_weights(meshTable, vertexId);

            const mat4 skinningMatrix = skinning_calculate_weighted_matrix(chunks, inJointIndices, inJointWeights);

            const vec4 positionWS = skinningMatrix * vec4(inPosition, 1);

            triangleWS.v[i] = positionWS.xyz;
        }
    }

    barycentric_coords bc, bcDDX, bcDDY;
    vec3 positionWS;

    if (!visibility_calculate_position_and_barycentric_coords(uvec2(screenPos),
            resolution,
            g_Camera,
            triangleWS,
            positionWS,
            bc,
            bcDDX,
            bcDDY))
    {
        write_empty_pixel(screenPos);
        return;
    }

    // Interpolate UV0 and calculate gradients
    const vec2 uv0 = barycentric_interpolate(bc, triangleUV0);

    vec2 uv0DDX, uv0DDY;
    barycentric_partial_derivatives(bcDDX, bcDDY, uv0, triangleUV0, uv0DDX, uv0DDY);

    vec3 normalWS;

    if (material.normalMapTexture != 0)
    {
        const vec4 sampledNormal = normal_map_sample_grad(material.normalMapTexture, uv0, uv0DDX, uv0DDY);

        const vec3 T = normalize(barycentric_interpolate(bc, triangleTangent));
        const vec3 B = normalize(barycentric_interpolate(bc, triangleBitangent));
        const vec3 N = normalize(barycentric_interpolate(bc, triangleNormal));

        normalWS = normal_map_apply(sampledNormal, T, B, N, mat3(transform.normalMatrix));
    }
    else
    {
        const vec3 N = barycentric_interpolate(bc, triangleNormal);
        normalWS = normalize(mat3(transform.normalMatrix) * N);
    }

    // Extract the PBR parameters from the material
    const pbr_material pbr = pbr_extract_parameters(material, uv0, uv0DDX, uv0DDY);

    gbuffer0 g0;
    gbuffer1 g1;
    gbuffer2 g2;
    gbuffer3 g3;

    g0.position = positionWS;
    g0.roughness = pbr.roughness;

    g1.normal = normalWS;

    g2.albedo = pbr.albedo;
    g2.metalness = pbr.metalness;

    g3.emissive = pbr.emissive;
    g3.ior = pbr.ior;

    imageStore(t_OutGBuffer0, screenPos, gbuffer_pack(g0));
    imageStore(t_OutGBuffer1, screenPos, gbuffer_pack(g1));
    imageStore(t_OutGBuffer2, screenPos, gbuffer_pack(g2));
    imageStore(t_OutGBuffer3, screenPos, gbuffer_pack(g3));
}