#version 460

#extension GL_GOOGLE_include_directive : require

#include <surfels/buffers/surfel_grid_data_w>
#include <surfels/buffers/surfel_grid_w>
#include <surfels/surfel_data>

layout(std430, binding = 0) restrict writeonly buffer b_SurfelsGridFill
{
    uint g_SurfelGridCellNextSurfelIndex[];
};

layout(local_size_x = OBLO_SUBGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform c_PushConstants
{
    surfel_grid_header gridHeader;
    uint gridHashMask;
}
g_Constants;

void main()
{
    const uint hashEntriesCount = g_Constants.gridHashMask + 1;
    const uint cellIndex = gl_GlobalInvocationID.x;

    if (cellIndex == 0)
    {
        g_SurfelGridHeader = g_Constants.gridHeader;
        g_SurfelGridCellDataIndex = 0;
        g_SurfelGridHashMask = g_Constants.gridHashMask;
    }

    if (gl_GlobalInvocationID.x >= hashEntriesCount)
    {
        return;
    }

    g_SurfelGridCells[cellIndex].surfelsCount = 0;
    g_SurfelGridCellNextSurfelIndex[cellIndex] = 0;
}