name: Win64 clang-cl Debug

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Configure CMake
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
        cmake -B ${{github.workspace}}/build --preset windows-clang-cl-debug

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

