name: Win64 clang-cl Debug

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Win64 clang-cl Debug
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
        submodules: 'true'

    - name: Configure CMake
      shell: cmd # Run cmd to keep the vcvars, then switch to powershell to configure
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
        powershell
        cmake -B ${{github.workspace}}/build --preset windows-clang-cl-debug

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

