name: Win64 vs2022 Debug

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Win64 vs2022 Debug
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
        submodules: 'true'

    - name: Configure CMake
      shell: powershell
      run: cmake -B ${{github.workspace}}/build --preset windows-vs2022

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

